name: Release

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger the workflow on tags that match the version format (e.g., v1.0.0)

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Specify the Node.js version to use

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build
        env:
          NODE_ENV: production

      - name: Generate Release Notes
        id: release-notes
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./path/to/your/asset
          asset_name: asset.zip
          asset_content_type: application/zip
